### PR TITLE
Added a folder named Navigation Button Styling

### LINKED ISSUE #11: Adding a basic template for responsive navigation bars
**Is your feature request related to a problem? Please describe.**
No. I wanted to contribute to the project by creating a template/example for a responsible navigation bar that could create a starting point for others with their webpages. The HTML and CSS remain basic so that customization would be easy for beginners to change and learn more about styling. 

**Describe the solution you'd like**
I've attached a video of what the CSS styles look like on the navigation bar.

**Additional context**
https://user-images.githubusercontent.com/112649525/194790706-73bb1d78-0a9a-4459-8930-02d3e0a3ac3a.mp4

Thank you for your time!

### PR DESCRIPTION
**Pull request by vita-tran**
## What is the change?
Created a simple design for a navigation bar that can be used for any webpage. Ran the code through validators and Prettier to make sure there were not errors. 

Close: #11 

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes [x]:
-   [X] Have you followed the [Contribution Guidelines](https://github.com/Bhaviktutorials/Adorn/blob/main/Contributing.md)while contributing.
-   [X] Have you checked there aren't other open [Pull Requests](https://github.com/Bhaviktutorials/Adorn/pulls) for the same update/change?
-   [X] Have you made corresponding changes to the documentation?
-   [X] Have you tested the code before submission?
-   [X] Have you formatted your code ? (You can use any html,css beautifier)
-   [X] My changes generates no new warnings.
-   [X] I'm HSOC22 contributor.
-   [X] I have commented my code, particularly in hard-to-understand areas.

## GIF/video of the working of component you created:

https://user-images.githubusercontent.com/112649525/194801743-ea12c2c7-f678-4c21-93c3-cfbb3a0d4f0f.mp4

### CODE REVIEW

**Review by Bhaviktutorials — CHANGES_REQUESTED** [review]
Everything is perfect but please do Update Table of content in readme.md under Elements Folder.

**Review by Bhaviktutorials — CHANGES_REQUESTED** [review]
Everything is perfect but please do Update Table of content in readme.md under Elements Folder.

**Review by Bhaviktutorials — APPROVED** [review]

**Comment by vita-tran** [comment]
Sorry about that! I just updated the Table of Contents - thank you!

**Comment by Bhaviktutorials** [comment]
**Thank You For Contributing**

**Pull request merged**
